# Generated by Django 4.2.2 on 2023-07-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WinCartDetail",
            fields=[
                ("cart_det_id", models.AutoField(primary_key=True, serialize=False)),
                ("cart_det_qnty", models.IntegerField()),
            ],
            options={
                "db_table": "win_cart_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinPurchase",
            fields=[
                ("purchase_id", models.AutoField(primary_key=True, serialize=False)),
                ("purchase_time", models.DateTimeField()),
                ("purchase_number", models.IntegerField()),
                ("purchase_price", models.IntegerField()),
            ],
            options={
                "db_table": "win_purchase",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinReceiveCode",
            fields=[
                (
                    "receive_code_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("receive_code", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "win_receive_code",
            },
        ),
        migrations.CreateModel(
            name="WinPurchaseDetail",
            fields=[
                (
                    "purchase_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("purchase_det_number", models.IntegerField()),
                ("purchase_det_price", models.IntegerField()),
                ("purchase_det_state", models.IntegerField()),
                (
                    "purchase",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="purchasing.winpurchase",
                    ),
                ),
                (
                    "sell",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.winsell",
                    ),
                ),
            ],
            options={
                "db_table": "win_purchase_detail",
            },
        ),
        migrations.CreateModel(
            name="WinCart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("cart_time", models.DateTimeField()),
                ("cart_state", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.winuser",
                    ),
                ),
            ],
            options={
                "db_table": "win_cart",
            },
        ),
    ]
