# Generated by Django 4.2.2 on 2023-07-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WinRevenue",
            fields=[
                ("revenue_id", models.AutoField(primary_key=True, serialize=False)),
                ("revenue_value", models.IntegerField()),
                ("revenue_date", models.DateTimeField()),
            ],
            options={
                "db_table": "win_revenue",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinSell",
            fields=[
                ("sell_id", models.AutoField(primary_key=True, serialize=False)),
                ("sell_reg_time", models.DateTimeField()),
                ("sell_price", models.IntegerField()),
                ("sell_promot", models.TextField()),
                ("sell_state", models.IntegerField()),
            ],
            options={
                "db_table": "win_sell",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinStore",
            fields=[
                ("store_id", models.AutoField(primary_key=True, serialize=False)),
                ("store_address", models.CharField(max_length=200)),
                ("store_name", models.CharField(max_length=100)),
                ("store_reg_num", models.CharField(max_length=20, unique=True)),
                ("store_email", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "win_store",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinStoreUrl",
            fields=[
                ("store_url_id", models.AutoField(primary_key=True, serialize=False)),
                ("store_map_url", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "win_store_url",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WinStoreExcel",
            fields=[
                ("store_excel_id", models.AutoField(primary_key=True, serialize=False)),
                ("store_excel", models.CharField(max_length=300)),
                (
                    "store",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.winstore",
                    ),
                ),
            ],
            options={
                "db_table": "win_store_excel",
            },
        ),
    ]
